id: PE6AADBA3
initial_creation_type: input
source_metadata:
  title: Khandro Tāre Lhamo Series
  language: en
  description: 'Texts by and about Khandro Tāre Lhamo (tA re lha mo, 1938–2003), who
    was one of the most prominent tertöns of recent times:'
  volume:
    280d51d2fec641fc8040cb9f5c66b227:
      title: Prayer for the Long Life of Khandro Tāre Lhamo
      parent: Long Life Prayers
created_at: '2022-03-01T00:16:37.518644'
last_modified_at: '2022-03-01T00:16:37.518650'
